import { PREPAREDNESS_PALETTE, CRISIS_PALETTE } from './palettes';
import { HomeIcon, DrillsIcon, MapIcon, ProfileIcon, LearnIcon, KitIcon, WeatherIcon, ArrowLeftIcon, ChevronRightIcon, TrophyIcon, QuizIcon, SimulationIcon, LanguageIcon, BellIcon, LogoutIcon, FirstAidIcon, WaterIcon, ShelterIcon, LightbulbIcon, SOSIcon, PhoneIcon, ShieldIcon, CheckCircleIcon, UserIcon, LockIcon } from './icons';
import { user, educationModules, badges, mapPoints, history, safetyKitItems, leaderboardData, survivalGuides, newsUpdates, emergencyContacts } from './mockData';

export {
    PREPAREDNESS_PALETTE,
    CRISIS_PALETTE,
    HomeIcon,
    DrillsIcon,
    MapIcon,
    ProfileIcon,
    LearnIcon,
    KitIcon,
    WeatherIcon,
    ArrowLeftIcon,
    ChevronRightIcon,
    TrophyIcon,
    QuizIcon,
    SimulationIcon,
    LanguageIcon,
    BellIcon,
    LogoutIcon,
    FirstAidIcon,
    WaterIcon,
    ShelterIcon,
    LightbulbIcon,
    SOSIcon,
    PhoneIcon,
    ShieldIcon,
    CheckCircleIcon,
    UserIcon,
    LockIcon,
    user,
    educationModules,
    badges,
    mapPoints,
    history,
    safetyKitItems,
    leaderboardData,
    survivalGuides,
    newsUpdates,
    emergencyContacts,
};